version: '3'
services:
 odoo:
  image: saicloud:12.0
  links:
   - 'db:db'
  ports:
   - "80:8069"
  # command: -- -c /etc/odoo/odoo.conf -d saicloud
  #command: -- -c /etc/odoo/odoo.conf -u account_account_reports -d saicloud
  volumes:
   - "/home/appdevelop/docker/12.0/odoo.conf:/etc/odoo/odoo.conf"
   - "/home/appdevelop/saicloud:/mnt/extra-addons/saicloud"
   - "/home/appdevelop/varios-saicloud:/mnt/extra-addons/varios-saicloud"
   - data-sai:/var/lib/odoo
 db:
  image: postgres:10.0
  environment:
   - POSTGRES_USER=odoo
   - POSTGRES_PASSWORD=odoo
  volumes:
   - data-sai-db:/var/lib/postgresql/data
volumes:
 data-sai:
 data-sai-db:
